# Generated by Django 4.2 on 2023-04-26 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_register', '0004_employee_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='profile_pic',
        ),
    ]
