# Generated by Django 4.2 on 2023-04-28 04:50

from django.db import migrations, models
import employee_register.models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_register', '0008_alter_employee_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to=employee_register.models.user_directory_path),
        ),
    ]
